version: "3.7"

services:
  app:
    image: dumbwareio/dumbpad:latest@sha256:6f8fb9b681152f17fc6f44cb1c7506ae691aa44ae13946f73fbf1c375ce84ea1
    restart: unless-stopped
    ports:
      - "${APP_PORT}:3000"
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
    environment:
      - TZ=${TZ}
