version: "3.7"

services:
  app:
    image: neosmemo/memos:stable
    restart: unless-stopped
    ports:
      - "${APP_PORT}:5230"
    volumes:
      - ${APP_DATA_DIR}/data:/var/opt/memos
    environment:
      - TZ=${TZ}
